# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudentLife' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StudentLife
  pod 'Firebase/Messaging'

  target 'StudentLife-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudentLifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
